dist: xenial
os: linux
language: go

env:
  global:
    - HUGO_VERSION=0.69.2
    - HUGO_ARCH=Linux-64bit

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_${HUGO_ARCH}.deb
  - sudo dpkg -i hugo_${HUGO_VERSION}_${HUGO_ARCH}.deb

script:
  - hugo

deploy:
  provider: pages:git
  token: $GITHUB_TOKEN
  edge: true
  local_dir: public
  repo: thingsym/vaw
  target_branch: gh-pages
  keep_history: true
  on:
    branch: master
    tags: true
    condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$
