# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Techdoc"
license = "MIT"
licenselink = "https://github.com/thingsym/hugo-theme-techdoc/LICENSE"
description = "The Techdoc is Hugo Theme for technical documentation."
homepage = "https://github.com/thingsym/hugo-theme-techdoc"
repo = "https://github.com/thingsym/hugo-theme-techdoc"
tags = ["documentation", "doc"]
features = ["documentation", "menu"]
min_version = "0.30"

[author]
  name = "thingsym"
  homepage = "https://blog.thingslabo.com/"
