name: Publish to Github Pages

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.121.2'
          extended: true

      - name: Build website
        run: hugo --minify

      - name: Deploy to GitHub Pages on external repository
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: thingsym/vaw
          publish_branch: gh-pages
          publish_dir: ./public
          commit_message: 'deploy to GitHub Pages via GitHub Actions'
